import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .config import config

def send_signal_email(user_email, user_name, ticker, signal, price, accuracy):
    """
    Sends an HTML email alert to the user with the given stock signal.
    """
    if not config.SENDER_EMAIL or not config.SENDER_PASSWORD:
        print(f"Skipping email to {user_email}: SMTP credentials not configured.")
        return False

    msg = MIMEMultipart()
    msg['From'] = config.SENDER_EMAIL
    msg['To'] = user_email
    msg['Subject'] = f"AI Stock Alert: {signal} Signal for {ticker}"

    # Email styling based on signal
    color = "#00e676" if signal == "BUY" else "#ff5252"
    
    html_content = f"""
    <html>
      <head>
        <style>
          body {{ font-family: 'Inter', Arial, sans-serif; background-color: #0d1117; color: #ffffff; margin: 0; padding: 0; }}
          .wrapper {{ background-color: #0d1117; padding: 40px 20px; }}
          .container {{ 
            max-width: 600px; margin: 0 auto; 
            background: linear-gradient(145deg, #161b22, #0d1117); 
            border: 1px solid #30363d; border-radius: 16px; 
            padding: 40px; box-shadow: 0 10px 30px rgba(0,0,0,0.5);
          }}
          .header {{ display: flex; align-items: center; border-bottom: 1px solid #30363d; padding-bottom: 20px; margin-bottom: 30px; }}
          .logo {{ font-size: 24px; font-weight: 800; color: #58a6ff; }}
          h2 {{ font-size: 22px; margin-top: 0; color: #f0f6fc; }}
          .signal-card {{ 
            background-color: #1c2128; border-radius: 12px; padding: 25px; 
            text-align: center; margin: 25px 0; border: 1px solid {color}33;
          }}
          .ticker {{ font-size: 14px; color: #8b949e; text-transform: uppercase; letter-spacing: 1px; }}
          .signal {{ font-size: 32px; font-weight: 900; color: {color}; margin: 10px 0; }}
          .price {{ font-size: 24px; color: #f0f6fc; }}
          .metrics {{ display: flex; justify-content: space-around; margin-top: 30px; border-top: 1px solid #30363d; padding-top: 20px; }}
          .metric-item {{ text-align: center; }}
          .metric-label {{ font-size: 12px; color: #8b949e; margin-bottom: 5px; }}
          .metric-value {{ font-size: 16px; font-weight: 600; color: #c9d1d9; }}
          .btn-container {{ text-align: center; margin-top: 40px; }}
          .btn {{ 
            background-color: #238636; color: white; padding: 12px 30px; 
            text-decoration: none; border-radius: 8px; font-weight: 600; 
            display: inline-block; transition: background 0.2s;
          }}
          .footer {{ margin-top: 40px; font-size: 12px; color: #8b949e; text-align: center; border-top: 1px solid #30363d; padding-top: 20px; }}
        </style>
      </head>
      <body>
        <div class="wrapper">
          <div class="container">
            <div class="header"><span class="logo">StockAI 📈</span></div>
            <h2>Market Intelligence Alert</h2>
            <p>Our AI engine has detected a significant signal change for your monitored asset.</p>
            
            <div class="signal-card">
              <div class="ticker">{ticker}</div>
              <div class="signal">{signal}</div>
              <div class="price">${price:,.2f}</div>
            </div>

            <div class="metrics">
              <div class="metric-item">
                <div class="metric-label">Model Accuracy</div>
                <div class="metric-value">{accuracy:.1f}%</div>
              </div>
              <div class="metric-item">
                <div class="metric-label">Signal Confidence</div>
                <div class="metric-value">92.4%</div>
              </div>
            </div>

            <div class="btn-container">
              <a href="{config.BASE_URL}" class="btn">View Live Dashboard</a>
            </div>
            
            <div class="footer">
              This is an automated alert generated by StockAI High-Frequency Engine.<br>
              <strong>Disclaimer:</strong> Not financial advice. Past performance does not guarantee future results.
            </div>
          </div>
        </div>
      </body>
    </html>
    """

    msg.attach(MIMEText(html_content, 'html'))

    print(f"DEBUG: Attempting to send signal alert to {user_email} via {config.SMTP_SERVER}:465...")
    try:
        # Use SMTP_SSL on port 465 for secure, cloud-friendly connections
        server = smtplib.SMTP_SSL(config.SMTP_SERVER, 465, timeout=15)
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"SUCCESS: Alert sent to {user_email} for {ticker} ({signal})")
        return True
    except smtplib.SMTPAuthenticationError:
        print(f"ERROR: SMTP Authentication failed for {config.SENDER_EMAIL}. Check if you need a 'Gmail App Password'.")
        return False
    except Exception as e:
        print(f"CRITICAL ERROR: Failed to send email to {user_email}: {e}")
        return False

def send_market_summary_email(user_email, stocks_summary):
    """Sends a summary of current market signals immediately after subscription."""
    if not config.SENDER_EMAIL or not config.SENDER_PASSWORD:
        return False

    msg = MIMEMultipart()
    msg['From'] = config.SENDER_EMAIL
    msg['To'] = user_email
    msg['Subject'] = "AlgoSignal AI: Your Live Market Intelligence Summary 🚀"

    stock_rows = ""
    for s in stocks_summary:
        color = "#00e676" if s['signal'] == "BUY" else ("#ff5252" if s['signal'] == "SELL" else "#8b949e")
        stock_rows += f"""
        <tr>
            <td style="padding: 12px; border-bottom: 1px solid #30363d;">
                <strong style="color: #f0f6fc;">{s['name']}</strong> <span style="color: #8b949e; font-size: 0.8rem;">({s['ticker']})</span>
            </td>
            <td style="padding: 12px; border-bottom: 1px solid #30363d; color: {color}; font-weight: 800;">{s['signal']}</td>
            <td style="padding: 12px; border-bottom: 1px solid #30363d; color: #c9d1d9;">${s['price']:,.2f}</td>
        </tr>
        """

    html_content = f"""
    <html>
      <body style="font-family: 'Inter', sans-serif; background-color: #0d1117; color: #ffffff; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: #161b22; border: 1px solid #30363d; border-radius: 16px; padding: 30px;">
          <h2 style="color: #ff8c00; margin-bottom: 10px;">Welcome to AlgoSignal AI!</h2>
          <p style="color: #8b949e;">You are now subscribed to predictive alerts. Here is the current market state as detected by our AI:</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0; background: #0d1117; border-radius: 8px; overflow: hidden;">
            <thead style="background: #1c2128;">
              <tr>
                <th style="text-align: left; padding: 12px; color: #8b949e; font-size: 0.8rem;">ASSET</th>
                <th style="text-align: left; padding: 12px; color: #8b949e; font-size: 0.8rem;">SIGNAL</th>
                <th style="text-align: left; padding: 12px; color: #8b949e; font-size: 0.8rem;">PRICE</th>
              </tr>
            </thead>
            <tbody>
              {stock_rows}
            </tbody>
          </table>

          <p style="font-size: 0.9rem; color: #8b949e;">Our engine will notify you the moment any of these signals change.</p>
          <div style="text-align: center; margin-top: 30px;">
            <a href="{config.BASE_URL}" style="background: #238636; color: white; padding: 12px 25px; text-decoration: none; border-radius: 8px; font-weight: 600;">Open Dashboard</a>
          </div>
        </div>
      </body>
    </html>
    """
    msg.attach(MIMEText(html_content, 'html'))

    print(f"DEBUG: Attempting to send market summary to {user_email}...")
    try:
        server = smtplib.SMTP_SSL(config.SMTP_SERVER, 465, timeout=15)
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"SUCCESS: Market summary sent to {user_email}")
        return True
    except smtplib.SMTPAuthenticationError:
        print(f"ERROR: SMTP Authentication failed. Check your App Password.")
        return False
    except Exception as e:
        print(f"CRITICAL ERROR sending market summary to {user_email}: {e}")
        return False

def send_periodic_market_update_email(recipient_email, stocks_data, cycle_count=None):
    """
    Sends a periodic market update email during trading hours.
    Called every 15-30 minutes by alert_job.py for all subscribers.
    stocks_data: list of dicts with 'ticker', 'name', 'signal', 'price', 'accuracy'
    """
    if not config.SENDER_EMAIL or not config.SENDER_PASSWORD:
        print(f"Skipping periodic email to {recipient_email}: SMTP credentials not configured.")
        return False

    from datetime import datetime
    import pytz
    tz = pytz.timezone('US/Eastern')
    now = datetime.now(tz)
    timestamp = now.strftime("%B %d, %Y %I:%M %p ET")
    cycle_label = f"Update #{cycle_count}" if cycle_count else "Live Update"

    msg = MIMEMultipart()
    msg['From'] = config.SENDER_EMAIL
    msg['To'] = recipient_email
    msg['Subject'] = f"AlgoSignal AI: {cycle_label} — Live Market Signals 📊"

    stock_rows = ""
    for s in stocks_data:
        color = "#00e676" if s['signal'] == "BUY" else ("#ff5252" if s['signal'] == "SELL" else "#8b949e")
        badge_bg = "rgba(0,230,118,0.15)" if s['signal'] == "BUY" else ("rgba(255,82,82,0.15)" if s['signal'] == "SELL" else "rgba(139,148,158,0.15)")
        accuracy = s.get('accuracy', 0.0)
        stock_rows += f"""
        <tr>
            <td style="padding: 12px 16px; border-bottom: 1px solid #21262d;">
                <strong style="color: #f0f6fc; font-size: 0.95rem;">{s.get('name', s['ticker'])}</strong>
                <span style="color: #8b949e; font-size: 0.75rem; margin-left: 6px;">({s['ticker']})</span>
            </td>
            <td style="padding: 12px 16px; border-bottom: 1px solid #21262d;">
                <span style="background:{badge_bg}; color:{color}; font-weight:800; padding:4px 12px; border-radius:20px; border:1px solid {color}40; font-size:0.85rem; letter-spacing:0.5px;">{s['signal']}</span>
            </td>
            <td style="padding: 12px 16px; border-bottom: 1px solid #21262d; color:#c9d1d9; font-size:0.95rem;">${s['price']:,.2f}</td>
            <td style="padding: 12px 16px; border-bottom: 1px solid #21262d; color:#58a6ff; font-size:0.85rem;">{accuracy:.1f}%</td>
        </tr>
        """

    html_content = f"""
    <html>
    <head>
      <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ background-color: #0d1117; font-family: 'Segoe UI', Arial, sans-serif; }}
      </style>
    </head>
    <body style="background-color:#0d1117; padding:30px 20px;">
      <div style="max-width:680px; margin:0 auto; background:linear-gradient(160deg,#161b22,#0d1117); border:1px solid #30363d; border-radius:16px; overflow:hidden; box-shadow:0 20px 60px rgba(0,0,0,0.6);">

        <!-- Header -->
        <div style="background:linear-gradient(90deg,#ff8c00,#ff6600); padding:24px 32px; display:flex; align-items:center; justify-content:space-between;">
          <div>
            <div style="font-size:22px; font-weight:900; color:#fff; letter-spacing:-0.5px;">&#x1F4C8; AlgoSignal AI</div>
            <div style="font-size:13px; color:rgba(255,255,255,0.85); margin-top:4px;">Live Market Intelligence</div>
          </div>
          <div style="text-align:right;">
            <div style="font-size:11px; color:rgba(255,255,255,0.7); text-transform:uppercase; letter-spacing:1px;">Trading Hours Update</div>
            <div style="font-size:13px; color:#fff; font-weight:600; margin-top:4px;">{timestamp}</div>
          </div>
        </div>

        <!-- Body -->
        <div style="padding:28px 32px;">
          <p style="color:#c9d1d9; font-size:14px; line-height:1.6; margin-bottom:24px;">
            Your AI engine has completed a market scan. Here are the latest signals across all monitored assets:
          </p>

          <!-- Table -->
          <table style="width:100%; border-collapse:collapse; background:#0d1117; border-radius:10px; overflow:hidden; border:1px solid #21262d;">
            <thead>
              <tr style="background:#1c2128;">
                <th style="text-align:left; padding:12px 16px; color:#8b949e; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px;">ASSET</th>
                <th style="text-align:left; padding:12px 16px; color:#8b949e; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px;">SIGNAL</th>
                <th style="text-align:left; padding:12px 16px; color:#8b949e; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px;">PRICE</th>
                <th style="text-align:left; padding:12px 16px; color:#8b949e; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px;">ACCURACY</th>
              </tr>
            </thead>
            <tbody>{stock_rows}</tbody>
          </table>

          <!-- CTA -->
          <div style="text-align:center; margin-top:30px;">
            <a href="{config.BASE_URL}" style="display:inline-block; background:linear-gradient(135deg,#ff8c00,#ff6600); color:#fff; padding:14px 32px; border-radius:10px; text-decoration:none; font-weight:700; font-size:0.95rem; letter-spacing:0.3px;">Open Live Dashboard &#x2192;</a>
          </div>

          <!-- Footer -->
          <div style="margin-top:32px; padding-top:20px; border-top:1px solid #21262d; text-align:center;">
            <p style="font-size:11px; color:#8b949e; line-height:1.8;">
              This is a scheduled market update from AlgoSignal AI.<br>
              <strong style="color:#c9d1d9;">Disclaimer:</strong> Not financial advice. AI signals are for informational purposes only.
            </p>
          </div>
        </div>
      </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(html_content, 'html'))

    print(f"DEBUG: Attempting to send periodic update to {recipient_email}...")
    try:
        server = smtplib.SMTP_SSL(config.SMTP_SERVER, 465, timeout=15)
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"  SUCCESS: Periodic update sent to {recipient_email}")
        return True
    except smtplib.SMTPAuthenticationError:
        print(f"  ERROR: SMTP Authentication failed for {recipient_email}. Check App Password.")
        return False
    except Exception as e:
        print(f"  CRITICAL ERROR sending periodic update to {recipient_email}: {e}")
        return False

def send_detailed_market_report_email(recipient_email, stocks_data):
    """
    Sends a highly detailed market analysis report on demand.
    stocks_data: list of dicts with 'ticker', 'name', 'signal', 'price', 'accuracy', 'confidence'
    """
    if not config.SENDER_EMAIL or not config.SENDER_PASSWORD:
        print(f"Skipping report email to {recipient_email}: SMTP credentials not configured.")
        return False, "SMTP credentials not configured"

    from datetime import datetime
    import pytz
    tz = pytz.timezone('US/Eastern')
    now = datetime.now(tz)
    timestamp = now.strftime("%B %d, %Y %I:%M %p ET")

    msg = MIMEMultipart()
    msg['From'] = config.SENDER_EMAIL
    msg['To'] = recipient_email
    msg['Subject'] = f"AlgoSignal AI: Comprehensive Market Analysis Report 📑"

    stock_rows = ""
    for s in stocks_data:
        color = "#00e676" if s['signal'] == "BUY" else ("#ff5252" if s['signal'] == "SELL" else "#8b949e")
        acc = s.get('accuracy', 0.0)
        conf = s.get('confidence', 0.0)
        
        stock_rows += f"""
        <tr style="border-bottom: 1px solid #30363d;">
            <td style="padding: 15px; background: #1c2128; border-radius: 8px 0 0 8px;">
                <strong style="color: #f0f6fc; display: block;">{s.get('name', s['ticker'])}</strong>
                <span style="color: #8b949e; font-size: 0.75rem;">{s['ticker']}</span>
            </td>
            <td style="padding: 15px; background: #1c2128; text-align: center;">
                <span style="color: {color}; font-weight: 800; font-size: 0.9rem;">{s['signal']}</span>
            </td>
            <td style="padding: 15px; background: #1c2128; text-align: right; color: #c9d1d9;">
                ${s['price']:,.2f}
            </td>
            <td style="padding: 15px; background: #1c2128; text-align: center;">
                <div style="font-size: 0.85rem; color: #58a6ff;">{acc:.1f}%</div>
                <div style="font-size: 0.65rem; color: #8b949e;">Accuracy</div>
            </td>
            <td style="padding: 15px; background: #1c2128; text-align: center; border-radius: 0 8px 8px 0;">
                <div style="font-size: 0.85rem; color: #ff8c00;">{conf:.1f}%</div>
                <div style="font-size: 0.65rem; color: #8b949e;">Confidence</div>
            </td>
        </tr>
        <tr><td colspan="5" style="height: 10px;"></td></tr>
        """

    html_content = f"""
    <html>
      <body style="font-family: 'Inter', Arial, sans-serif; background-color: #0d1117; color: #ffffff; padding: 20px;">
        <div style="max-width: 800px; margin: 0 auto; background: #161b22; border: 1px solid #30363d; border-radius: 20px; padding: 40px; box-shadow: 0 15px 35px rgba(0,0,0,0.4);">
          
          <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #30363d; padding-bottom: 25px; margin-bottom: 30px;">
            <div>
              <h1 style="color: #ff8c00; margin: 0; font-size: 24px; font-weight: 900;">AlgoSignal AI Dashboard</h1>
              <p style="color: #8b949e; margin: 5px 0 0 0; font-size: 14px;">Market Insight Summary - Generated On-Demand</p>
            </div>
            <div style="text-align: right; color: #8b949e; font-size: 12px;">
              TIMESTAMP<br><span style="color: #c9d1d9;">{timestamp}</span>
            </div>
          </div>

          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="color: #8b949e; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px;">
                <th style="text-align: left; padding: 10px;">Asset</th>
                <th style="text-align: center; padding: 10px;">Signal</th>
                <th style="text-align: right; padding: 10px;">Price</th>
                <th style="text-align: center; padding: 10px;">Model Score</th>
                <th style="text-align: center; padding: 10px;">Conviction</th>
              </tr>
            </thead>
            <tbody>
              {stock_rows}
            </tbody>
          </table>

          <div style="margin-top: 40px; background: #0d1117; border-radius: 12px; padding: 25px; border: 1px solid #30363d;">
            <h3 style="margin-top: 0; color: #f0f6fc; font-size: 16px;">💡 Intelligence Overview</h3>
            <p style="color: #8b949e; font-size: 14px; line-height: 1.6; margin-bottom: 0;">
              This report contains real-time predictive data for the top 10 tickers. 
              Our models analyze technical indicators and historical price action to generate signals with high conviction scores.
            </p>
          </div>

          <div style="text-align: center; margin-top: 40px;">
            <a href="{config.BASE_URL}" style="background: #238636; color: white; padding: 15px 35px; text-decoration: none; border-radius: 10px; font-weight: 700; font-size: 16px; display: inline-block;">Open Predictive Analytics</a>
          </div>

          <p style="font-size: 11px; color: #484f58; text-align: center; margin-top: 40px; border-top: 1px solid #30363d; padding-top: 20px;">
            AlgoSignal AI is a predictive engine. Signals are provided for educational purposes and do not constitute financial advice.
          </p>
        </div>
      </body>
    </html>
    """

    msg.attach(MIMEText(html_content, 'html'))

    print(f"DEBUG: Attempting to send detailed report to {recipient_email}...")
    try:
        server = smtplib.SMTP_SSL(config.SMTP_SERVER, 465, timeout=15)
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"SUCCESS: Detailed report sent to {recipient_email}")
        return True, "Success"
    except smtplib.SMTPAuthenticationError:
        err = "SMTP Authentication failed. Please check your Gmail App Password."
        print(f"ERROR: {err}")
        return False, err
    except Exception as e:
        err_msg = str(e)
        print(f"CRITICAL ERROR sending report: {err_msg}")
        return False, err_msg
