import plotly.graph_objects as go
import pandas as pd

def plot_candlestick_with_signals(df, ticker, title="Price Action & ML Signals"):
    """
    Generate a high-quality Plotly candlestick chart with Buy/Sell markers.
    """
    # Slice the last 6 months for clear visualization
    df_plot = df.iloc[-120:].copy()
    
    fig = go.Figure()

    # Candlestick
    fig.add_trace(go.Candlestick(
        x=df_plot.index,
        open=df_plot['open'],
        high=df_plot['high'],
        low=df_plot['low'],
        close=df_plot['close'],
        name='Price (Candlestick)',
        increasing_line_color='#26a69a',
        decreasing_line_color='#ef5350'
    ))
    
    # Moving Averages overlay
    if 'sma_20' in df_plot.columns:
        fig.add_trace(go.Scatter(x=df_plot.index, y=df_plot['sma_20'],
            mode='lines', line=dict(color='rgba(255, 165, 0, 0.6)', width=1.5), name='SMA 20'))
    if 'sma_50' in df_plot.columns:
        fig.add_trace(go.Scatter(x=df_plot.index, y=df_plot['sma_50'],
            mode='lines', line=dict(color='rgba(138, 43, 226, 0.6)', width=1.5), name='SMA 50'))

    # Plot Buy/Sell Markers based on the `Signal` column (generated by the model historically)
    buys = df_plot[df_plot['Signal'] == 'BUY']
    sells = df_plot[df_plot['Signal'] == 'SELL']

    if not buys.empty:
        fig.add_trace(go.Scatter(
            x=buys.index, y=buys['low'] * 0.98,
            mode='markers',
            marker=dict(symbol='triangle-up', size=12, color='#00E676', line=dict(width=1, color='DarkSlateGrey')),
            name='ML Buy Signal'
        ))

    if not sells.empty:
        fig.add_trace(go.Scatter(
            x=sells.index, y=sells['high'] * 1.02,
            mode='markers',
            marker=dict(symbol='triangle-down', size=12, color='#FF1744', line=dict(width=1, color='DarkSlateGrey')),
            name='ML Sell Signal'
        ))

    # Styling for simple, dynamic, premium aesthetic
    fig.update_layout(
        title=f"{ticker} - {title}",
        title_font=dict(size=20, family="Inter", color="white"),
        template="plotly_dark",
        xaxis_rangeslider_visible=False,
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(20, 20, 24, 1)", # Sleek dark mode background
        margin=dict(l=40, r=40, t=50, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    
    return fig

def plot_probability_gauge(probability, signal):
    """
    Creates a premium probability gauge chart.
    """
    color = "gray"
    if signal == "BUY":
        color = "#00E676"
    elif signal == "SELL":
        color = "#FF1744"
        
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=probability,
        domain={'x': [0, 1], 'y': [0, 1]},
        title={'text': f"Confidence", 'font': {'size': 18, 'color': 'white'}},
        gauge={
            'axis': {'range': [0, 100], 'tickwidth': 1, 'tickcolor': "white"},
            'bar': {'color': color},
            'bgcolor': "rgba(255,255,255,0.1)",
            'borderwidth': 0,
            'steps': [
                {'range': [0, 40], 'color': 'rgba(255, 255, 255, 0.05)'},
                {'range': [40, 70], 'color': 'rgba(255, 255, 255, 0.1)'},
                {'range': [70, 100], 'color': 'rgba(255, 255, 255, 0.15)'}
            ]
        }
    ))
    
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        height=250,
        margin=dict(l=20, r=20, t=40, b=20)
    )
    return fig

def plot_equity_curve(df, ticker):
    """
    Plots the cumulative strategy returns (Equity Curve).
    """
    if 'equity_curve' not in df.columns:
        return None
        
    fig = go.Figure()
    
    fig.add_trace(go.Scatter(
        x=df.index, 
        y=df['equity_curve'],
        mode='lines',
        line=dict(color='#00c8ff', width=3),
        fill='tozeroy',
        fillcolor='rgba(0, 200, 255, 0.1)',
        name='ML Strategy Performance'
    ))
    
    fig.update_layout(
        title=f"{ticker} Strategy Equity Curve (Performance)",
        title_font=dict(size=18, family="Inter", color="white"),
        template="plotly_dark",
        paper_bgcolor="rgba(20, 20, 24, 1)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=40, r=40, t=50, b=40),
        yaxis_title="Growth of $1",
        xaxis_title="Date",
        xaxis=dict(showgrid=False),
        yaxis=dict(gridcolor="rgba(255,255,255,0.05)")
    )
    
    return fig
